### ISSUE TITLE
Changes for .Net 8?

### ISSUE THREAD

**Issue by vindberg** [DavidVollmers/Ignis#33]
Hi, I was wondering what changes are coming now that .net 8 has some of the same features as your solution.

I wish I had seen your project earlier, could have saved me a lot of work, especially with double reload of serverprerendered :)

Thanks for doing this open source!

**Comment by DavidVollmers** [comment]
Thank you very much 😄 

I am currently still investigating when it comes to .NET 8, but so far I did not see anything which could be breaking Ignis.
In fact Ignis will only profit from the cool new features introduced with .NET 8 (Blazor United for example).

But if you have any specific features in mind please tell me!

**Comment by vindberg** [comment]
My primary problems was SEO issues related to trying to fix the double event on initial load. Secondly, the reconnect of sockets is a big problem.

I think both issues has been solved for me in .Net 8. I guess your solution mitigated the same issues.

**Comment by DavidVollmers** [comment]
What I can see so far from .NET 8 is that components rendered using render mode `ServerPrerendered` will still trigger the events twice. When it comes to sockets I am not sure what exactly you mean.

**Comment by vindberg** [comment]
The lost socket connection is detailed here: https://github.com/dotnet/aspnetcore/issues/30344#issuecomment-1740463872

The reconnect message is awful, especially for mobile users that occasionally loose internet connection.

I will investigate the double trigger further, thanks 👍

**Comment by DavidVollmers** [comment]
I see thank you. This issue unfortunately will also happen using Ignis when rendering server side components. Ignis does implement its own components but is still attached to the Blazor circuit.

**Comment by DavidVollmers** [comment]
I will close this for now. Once .NET 8 is released I will also release an update for Ignis to support it!
