### ISSUE TITLE
Question: Full Headless UI support?

### ISSUE THREAD

**Issue by markmonster** [DavidVollmers/Ignis#34]
As I understand there is Headless UI support. Does this mean components written against Headless UI can more or less be used? What about for example the Tailwind UI Component Library which builds on top of Headless UI?

**Comment by DavidVollmers** [comment]
Hi there!

Yes Ignis provides a mostly complete (combobox is missing) port of all Headless UI components via the [Ignis.Components.HeadlessUI](https://www.nuget.org/packages/Ignis.Components.HeadlessUI) package.

This means that all components have been written from scratch using Ignis/Blazor but maintaining the same behavior as the React/Vue components from Headless UI do. You can have a look on all of them with example code [here](https://ignis.dvolper.dev/docs/components/headlessUI).

By the way there is also a package to port all hero icons: [Ignis.Components.HeroIcons](https://www.nuget.org/packages/Ignis.Components.HeroIcons)

With these two packages you are able to build all Tailwind UI components & templates using Ignis & Blazor. This is what I do in my private projects and one of the big reasons why I created Ignis!

**Comment by DavidVollmers** [comment]
As example you can take the project website ([ignis.dvolper.dev](https://ignis.dvolper.dev/)) which is build using Ignis and the [Tailwind UI Syntax template](https://tailwindui.com/templates/syntax).

**Comment by DavidVollmers** [comment]
I will close this issue as the question is answered. Feel free to open another issue if you encounter any problems or have more questions!
