### ISSUE TITLE
Issue creating HeadlessUi Components

### ISSUE THREAD

**Issue by TobiasBCC** [DavidVollmers/Ignis#35]
Hey,
i'm getting the  following error while creating a dialog  with HeadlessUI (Blazor  WASM).

![image](https://github.com/DavidVollmers/Ignis/assets/123938891/6d7d9434-5dc9-40d7-baf1-a4d4b90c86d5)

I have the following packages intalled:
![image](https://github.com/DavidVollmers/Ignis/assets/123938891/96465b80-7000-49bb-977b-3f26aef375cc)

Thanks  for your help.

**Comment by DavidVollmers** [comment]
Hi you need to add the `Ignis.Components.Web` js file to your project in order to make some of the Headless UI components (e.g., Dialog) work.

You can do this by adding the following script element to your `index.html`:
```html
<script defer type="text/javascript" src="~/_content/Ignis.Components.Web/min.js"></script>
``` 

This is also described [here](https://ignis.dvolper.dev/docs/components/packages).

**Comment by TobiasBCC** [comment]
> Hi you need to add the `Ignis.Components.Web` js file to your project in order to make some of the Headless UI components (e.g., Dialog) work.
> 
> You can do this by adding the following script element to your `index.html`:
> 
> ```
> <script defer type="text/javascript" src="_content/Ignis.Components.Web/min.js"></script>
> ```
> 
> This is also described [here](https://ignis.dvolper.dev/docs/components/packages).

Thanks for your answer, this helped me a lot.
Now I  have a last problem. When I'm gonna create a basic Ignis WASM-App, everything is fine.
So  i've added a TestPage.razor and placed the code from here (modal) [ModalCode](https://ignis.dvolper.dev/docs/components/headlessUI/dialog)
It look likes this, why?
![image](https://github.com/DavidVollmers/Ignis/assets/123938891/ba1c28f1-780c-4073-aa24-263292259de0)

My Code:
`@page "/test"
@using Ignis.Components
@using Ignis.Components.HeadlessUI
@using Ignis.Utils

@inherits IgnisComponentBase

<div class="absolute inset-0 flex items-center justify-center">
    <button type="button"
            @onclick="OpenModal"
            class="rounded-md bg-black bg-opacity-20 px-4 py-2 text-sm font-medium text-white hover:bg-opacity-30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75">
        Open dialog
    </button>

    <Transition Appear Show="_isOpen" AsComponent="typeof(Fragment)" Context="_">
        <Dialog class="z-10" IsOpenChanged="v => _isOpen = v" IgnoreOutlet>
            <TransitionChild AsComponent="typeof(Fragment)"
                             Enter="ease-out duration-300"
                             EnterFrom="opacity-0"
                             EnterTo="opacity-100"
                             Leave="ease-in duration-200"
                             LeaveFrom="opacity-100"
                             LeaveTo="opacity-0"
                             Context="transition">
                <div class="@Css.Class("absolute inset-0 bg-black bg-opacity-25", transition)"></div>
            </TransitionChild>

            <div class="absolute inset-0 overflow-y-auto">
                <div class="flex min-h-full items-center justify-center p-4 text-center">
                    <TransitionChild AsComponent="typeof(Fragment)"
                                     Enter="ease-out duration-300"
                                     EnterFrom="opacity-0 scale-95"
                                     EnterTo="opacity-100 scale-100"
                                     Leave="ease-in duration-200"
                                     LeaveFrom="opacity-100 scale-100"
                                     LeaveTo="opacity-0 scale-95"
                                     Context="transition">
                        <DialogPanel class="@Css.Class("w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all", transition)">
                            <DialogTitle AsElement="h3"
                                         class="text-lg font-medium leading-6 text-gray-900">
                                Payment successful
                            </DialogTitle>
                            <div class="mt-2">
                                <p class="text-sm text-gray-500">
                                    Your payment has been successfully submitted. We’ve sent
                                    you an email with all of the details of your order.
                                </p>
                            </div>

                            <div class="mt-4">
                                <button type="button"
                                        class="inline-flex justify-center rounded-md border border-transparent bg-blue-100 px-4 py-2 text-sm font-medium text-blue-900 hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
                                        @onclick="CloseModal">
                                    Got it, thanks!
                                </button>
                            </div>
                        </DialogPanel>
                    </TransitionChild>
                </div>
            </div>
        </Dialog>
    </Transition>
</div>

@code
{
    private bool _isOpen = true;

    private void OpenModal()
    {
        _isOpen = true;

        Update();
    }

    private void CloseModal()
    {
        _isOpen = false;

        Update();
    }
}`

**Comment by DavidVollmers** [comment]
Yes the example code from the website uses [Tailwind CSS](https://tailwindcss.com/) to style the components. You will need to set this up in your project or use something else to style the components.

To quickly try out Ignis and Headless UI, I recommend to use the WebAssembly project template:
```shell
dotnet new ignis-wasm
```

This will setup a new project using Blazor WebAssembly, Ignis, Headless UI and Tailwind CSS. There you can copy and paste the example code from the website and it will work. You can read more about the project templates [here](https://ignis.dvolper.dev/docs/).

**Comment by DavidVollmers** [comment]
If you still have trouble with this, please feel free to create a public repository so that I can have a more detailed look on the problem.

**Comment by TobiasBCC** [comment]
> Owner

Hey, still the same, here is a repo:
[Ignis-Modal-Test-Repo](https://github.com/TobiasBCC/ignis_modal_test.git)

**Comment by TobiasBCC** [comment]
> @TobiasBCC If you still have trouble with this, please feel free to create a public repository so that I can have a more detailed look on the problem.

Oh sorry, I have to runa gain "npm run build", now it's  working  :)
