### ISSUE TITLE
Make closing dialog when clicking next to it optional

### ISSUE THREAD

**Issue by NathanVG** [DavidVollmers/Ignis#58]
While in a lot of cases the behavior of closing a dropdown menu or a dialog when clicking next to it is desirable, in other cases, where you require a user to select something this behavior is not ideal. 

I would like to propose adding a flag to the dialog component so this behavior can be disabled at will , like the IgnoreOutlet flag.

**Comment by NathanVG** [comment]
Ah great, maybe this should be mentioned in the docs :)

**Comment by DavidVollmers** [comment]
Unfortunately there is a lot which currently isn't mentioned in the docs, but yes I agree!
